//! Crate-internal test suites.

mod canonical_tests;
mod census_tests;
mod commitment_oracle_tests;
mod confidential_fixture_tests;
mod confidential_funding_tests;
mod confidential_record_tests;
mod conservation_three_way_tests;
mod constructor_matrix_tests;
mod constructor_tests;
mod emit_tests;
mod fixture_tests;
mod guide11_reproductions;
mod guide12_reproductions;
mod guide13_reproductions;
mod live_receipt_key_tests;
mod normalization_matrix_tests;
mod operation_boundary_tests;
mod owner_authorization_tests;
mod owner_key_oracle_tests;
mod protocol_tests;
mod prototype_program_tests;
mod prototype_tests;
mod prototype_validate_tests;
mod provenance_tests;
mod reference_oracle_tests;
pub mod support;
mod test_material_tests;
mod validate_tests;
mod vocabulary_tests;
mod wide_floor_matrix_tests;
mod wide_floor_program_tests;
mod wide_floor_tests;
