option('xelatex_path', type: 'string', value: '', description: 'Path to xelatex program')
option('biber_path', type: 'string', value: '', description: 'Path to biber program')
option('latexmk_path', type: 'string', value: '', description: 'Path to latexmk program')
option('git_path', type: 'string', value: '', description: 'Path to git program')
option('jq_path', type: 'string', value: '', description: 'Path to jq program')
